### PR TITLE
Upgrade redmine to version v3.3.7

### PR DESCRIPTION
**Pull request by philhug**

### CODE REVIEW

**Comment by J0WI** [comment]
Why not just `3.3`? It should be save to allow minor updates.

**Comment by philhug** [comment]
I don't think you want to just auto-deploy a new version after a reboot

**Comment by J0WI** [comment]
> I don't think you want to just auto-deploy a new version after a reboot

Do we actively pull on startup?

**Comment by philhug** [comment]
in that case we have to switch the base image. e.g. by directly switching to the upstream image instead of the sameersbn image.
do you know why the extra dependencies were added? are those used by any of our plugins?

**Comment by J0WI** [comment]
It seems that you've added them for the DMSF plugin: https://github.com/ppschweiz/docker-redmine/commit/d416ac1037bd9b20b0424ea4977cb41d08fd4c18#diff-3254677a7917c6c01f55212f86c57fbf
I'd definitively prefer using the upstream base image. Please also consider upgrading to Redmine 3.4 (DMSF is compatible).

**Comment by cambid** [comment]
@philhug: Please change the passwords in this PR back to the usage of the values from hashi_vault.
@J0WI: I would prefer moving to 3.4.7-1 based on the sameersbn-image first and doing the migration to the official upstream image in a second task.

**Comment by J0WI** [comment]
So this PR is not needed at all, we can just build/pull the new version (see https://github.com/ppschweiz/docker-redmine/commit/879f00cb917b22d7c0bde2d951ec9318f409c67c#diff-3254677a7917c6c01f55212f86c57fbf)

**Comment by J0WI** [comment]
3.3 reached EOL, 3.4.10 has just been released.
:ping_pong: @cambid @philhug

**Comment by cambid** [comment]
As we've deployed 3.4.10 today, I close this pull-request.

**Pull request closed without merging**
